let Texts = {
  sure: "Êtes-vous sûr de cette action?",
  offerLimited: "L’offre a atteint le nombre maximal de livreur.",
  start: "Commencé",
  active: "Actif",
  complete: "Completé",
  reject: "Annulé",
  fieldsRequired: "Les champs sont obligatoires",
  profileSuccess: "La mise à jour du profil a réussi",
  editProfile: "Editer le profil",
  inputAddress: "Entrez votre adresse",
  emailSent: "E-mail envoyé avec succès",
  enterEmail: "Entrez votre email pour réinitialiser le mot de passe",
  forgotPass: "Mot de passe oublié",
  invitationsHeading: "INVITATIONS RECUES",
  registerSuccess: "L'enregistrement a été réussi",
  emptyTable: "Aucune mission",
  nightHour: "Inclut tarif de nuit",
  totalEarning: "MONTANT TOTAL ACQUIS",
  missions: "MISSIONS VALIDÉES",
  noAction: "Pas d’action",
  note: "Noté",
  notes: "notés",
  cancel: "ANNULER",
  noter: "NOTER",
  profile: "Profil",
  hello: "Hello",
  update: "METTRE À JOUR",
  productPage: "Product",
  pricingPage: "Pricing",
  contactsPage: "Contacts",
  teamPage: "Team",
  emptySearch: "Pas de livreur trouvé",
  logout: "Se déconnecter",
  invitations: "TOUTES LES MISSIONS",
  deliveries: "TOUTES LES MISSIONS",
  userProfile: "Utilisateur Profil",
  searchTitle: "RECHERCHER UN LIVREUR",
  searchRating: "NOTE MINIMUM",
  searchDate: "DATE ET HEURE DE LA MISSION",
  searchDay: "JOUR :",
  searchHourStart: "HEURE DE DEMARRAGE :",
  searchHourEnd: "HEURE DE FIN :",
  searchDeliveries: "NOMBRE DE LIVREURS SOUHAITES :",
  searchStart: "RECHERCHER",
  resultTitle: "RESULTATS DE LA RECHERCHE",
  resultModify: "Modifier",
  resultInviter: "INVITER",
  resultInvited: "INVITED",
  labelFirstName: "Prenom *",
  labelLastName: "Nom *",
  labelAddress: "N° DE RUE ET RUE *",
  labelAddressHeading: "ADRESSE POSTALE",
  labelPostal: "CODE POSTAL *",
  labelComplement: "COMPLÉMENT D’ADRESSE",
  labelCity: "VILLE *",
  labelPhone: "NUMÉRO DE TÉLÉPHONE *",
  labelSIRET: "SIRET *",
  labelSIRET2: "NUMERO DE SIRET",
  labelDocumentsHeading: "JUSTIFICATIFS",
  done: "Terminé",
  step1: "SAISIE DE VOS INFORMATIONS",
  step2: "VALIDATION DE VOS INFORMATIONS",
  step3: "ACTIVATION DU COMPTE",
  loading: "Loading...",
  submitDocuments: "Soumettre mon dossier",
  step1Heading: "Validons ensemble vos informations",
  companyStep1Head: "Bienvenue sur",
  companyStep1Head1: "Chancee !",
  companyStep1ButtonText: "DÉMARRER",
  companyStep1Description:
    "Nous configurons votre espace personnel, plus que quelques étapes et votre profil sera disponible auprès de nos 2300+ restaurants partenaires",
  userStep2Head: "Votre profil a été",
  userStep2Head2: "validé Anne-Gabrielle !",
  userStep2ButtonText: "JE ME LANCE",
  userStep1Description:
    "Votre espace personnel a été activé, encore quelques informations et vous recevrez les offres de nos 2300+ restaurants partenaires",
  userStep2Heading: "Plus qu’une étape avant de démarrer !",
  userStep2HourIncrement:
    "Pour les missions de nuit (entre 20h et 8h), les tarifs sont automatiquement augmentés de 10%",
  userStep2Conditions1: "Je suis d’accord avec les",
  userStep2Conditions2: "Conditions d’utilisation",
  addTimeslot: "Ajouter la disponibilité",
};

export default Texts;
